name: Test and Deploy Docker Compose to Docker Hub

on:
  pull_request:
  push:
    branches:
      ["main", "testing", "devops/github-actions-support"]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore $SLN_PATH
      - name: Build
        run: dotnet build $SLN_PATH --no-restore
      - name: Test
        run: dotnet test $SLN_PATH --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          set -e
          docker-compose build
          for service in $(docker-compose config --services); do
            IMAGE_TAG=${GITHUB_SHA}
            echo "Pushing $service with tag $IMAGE_TAG..."
            docker tag $service:latest "$DOCKER_HUB_USERNAME/$service:$IMAGE_TAG"
            docker push "$DOCKER_HUB_USERNAME/$service:$IMAGE_TAG"
          done
        env:
          DOCKER_USERNAME: ${DOCKER_HUB_USERNAME}
          DOCKER_PASSWORD: ${DOCKER_HUB_PASSWORD}
